### ISSUE TITLE
数据库疑惑

### ISSUE THREAD

**Issue by wuaib** [kldhsh123/mahui#2]
关于admin那一行数据库我无法正常配置，在代码中为查到那些等级，可否搞一个代例子的数据库呢

**Comment by kldhsh123** [comment]
admin我自己都没搞明白，目前只是为了让插件跑起来设置的。

**Comment by wuaib** [comment]
那就不能用彩色标签和称号了

**Comment by kldhsh123** [comment]
是的,只能保证聊天等级UI等功能正常运行

**Comment by wuaib** [comment]
我去研究研究他这个数据库

**Comment by wuaib** [comment]
现在就admin给我带来疑惑了，其他数据库我以及完善好了

**Comment by kldhsh123** [comment]
方不方便加个qq1022140881交流呢?
